# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef28ad06e1fd937d22424687f6d0fdd9210ae61b73ba2aa281dca824bc78c5a5cdc2cf696411c1a1da4aa43e3e16b49bb30c80286e00c9b01755c6db455a699f

test:
  secret_key_base: b86c998d2e62bc13483559f16b9c6cb33267f183d045b7d970d0b5bf82ec0b923b5f663e6d06f93a48a7538e3396c95710b608ccfd50cdedb285598918c2a470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
